/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/q11bMDlHdbQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function landing() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Slick Solutions</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Features
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Pricing
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Unlock the Power of Slick Solutions
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Revolutionize your business with our cutting-edge SaaS application, featuring real-time
                    communications, AI-powered scheduling, and seamless multi-tenancy.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-[#00AE98]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Get Started
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Schedule a Demo
                  </Link>
                </div>
              </div>
              <div className="relative">
                <div className="absolute top-0 left-0 w-full h-full overflow-hidden rounded-xl">
                  <div className="w-full h-full bg-gradient-to-r from-[#00AE98] to-[#00D8C9] opacity-50 blur-[100px]" />
                  <div className="w-full h-full bg-gradient-to-r from-[#00AE98] to-[#00D8C9] opacity-50 blur-[50px]" />
                </div>
                <div className="relative z-10 w-full h-full">
                  <div className="w-full h-full flex items-center justify-center">
                    <div className="w-[400px] h-[400px] relative">
                      <div className="absolute top-0 left-0 w-full h-full">
                        <svg viewBox="0 0 400 400" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <defs>
                            <linearGradient id="gradient" x1="0" y1="0" x2="1" y2="1">
                              <stop offset="0%" stopColor="#00AE98" />
                              <stop offset="100%" stopColor="#00D8C9" />
                            </linearGradient>
                          </defs>
                          <path
                            d="M200 0C89.5431 0 0 89.5431 0 200C0 310.457 89.5431 400 200 400C310.457 400 400 310.457 400 200C400 89.5431 310.457 0 200 0Z"
                            fill="url(#gradient)"
                          />
                          <path
                            d="M200 0C89.5431 0 0 89.5431 0 200C0 310.457 89.5431 400 200 400C310.457 400 400 310.457 400 200C400 89.5431 310.457 0 200 0Z"
                            fill="url(#gradient)"
                            className="animate-rotate"
                          />
                          <path
                            d="M200 0C89.5431 0 0 89.5431 0 200C0 310.457 89.5431 400 200 400C310.457 400 400 310.457 400 200C400 89.5431 310.457 0 200 0Z"
                            fill="url(#gradient)"
                            className="animate-rotate-reverse"
                          />
                        </svg>
                      </div>
                      <div className="absolute top-0 left-0 w-full h-full">
                        <svg viewBox="0 0 400 400" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <defs>
                            <linearGradient id="gradient2" x1="0" y1="0" x2="1" y2="1">
                              <stop offset="0%" stopColor="#00D8C9" />
                              <stop offset="100%" stopColor="#00AE98" />
                            </linearGradient>
                          </defs>
                          <path
                            d="M200 0C89.5431 0 0 89.5431 0 200C0 310.457 89.5431 400 200 400C310.457 400 400 310.457 400 200C400 89.5431 310.457 0 200 0Z"
                            fill="url(#gradient2)"
                          />
                          <path
                            d="M200 0C89.5431 0 0 89.5431 0 200C0 310.457 89.5431 400 200 400C310.457 400 400 310.457 400 200C400 89.5431 310.457 0 200 0Z"
                            fill="url(#gradient2)"
                            className="animate-rotate"
                          />
                          <path
                            d="M200 0C89.5431 0 0 89.5431 0 200C0 310.457 89.5431 400 200 400C310.457 400 400 310.457 400 200C400 89.5431 310.457 0 200 0Z"
                            fill="url(#gradient2)"
                            className="animate-rotate-reverse"
                          />
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="features" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Key Features</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Unlock the Power of Slick Solutions</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Revolutionize your business with our cutting-edge SaaS application, featuring real-time
                  communications, AI-powered scheduling, and seamless multi-tenancy.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:gap-12 lg:grid-cols-3">
              <div className="grid gap-1">
                <div className="bg-primary rounded-md p-3 flex items-center justify-center">
                  <VideoIcon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="text-lg font-bold">Real-time Communications</h3>
                <p className="text-sm text-muted-foreground">
                  Empower your team with real-time video, audio, and chat capabilities, enabling seamless collaboration.
                </p>
              </div>
              <div className="grid gap-1">
                <div className="bg-primary rounded-md p-3 flex items-center justify-center">
                  <CalendarIcon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="text-lg font-bold">AI Appointment Scheduling System</h3>
                <p className="text-sm text-muted-foreground">
                  Streamline your scheduling with our AI-powered appointment system, ensuring optimal resource
                  utilization.
                </p>
              </div>
              <div className="grid gap-1">
                <div className="bg-primary rounded-md p-3 flex items-center justify-center">
                  <ClipboardIcon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="text-lg font-bold">Client Self-Assessment System</h3>
                <p className="text-sm text-muted-foreground">
                  Empower your clients with a self-assessment tool, providing personalized recommendations and insights.
                </p>
              </div>
              <div className="grid gap-1">
                <div className="bg-primary rounded-md p-3 flex items-center justify-center">
                  <ImageIcon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="text-lg font-bold">CNN Model for Image Assessment</h3>
                <p className="text-sm text-muted-foreground">
                  Leverage our advanced CNN model to assist with image-based assessments, streamlining your workflow.
                </p>
              </div>
              <div className="grid gap-1">
                <div className="bg-primary rounded-md p-3 flex items-center justify-center">
                  <UsersIcon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="text-lg font-bold">Multi-tenancy and Branding</h3>
                <p className="text-sm text-muted-foreground">
                  Seamlessly manage multiple clients and brands within a single platform, ensuring a tailored
                  experience.
                </p>
              </div>
              <div className="grid gap-1">
                <div className="bg-primary rounded-md p-3 flex items-center justify-center">
                  <InfoIcon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="text-lg font-bold">Analytics and Reporting</h3>
                <p className="text-sm text-muted-foreground">
                  Gain valuable insights into your business with our comprehensive analytics and reporting tools.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="pricing" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Pricing</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Flexible Pricing for Your Business</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Choose the plan that best fits your needs and scale as your business grows.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:gap-12 lg:grid-cols-3">
              <div className="grid gap-4 p-6 rounded-xl border">
                <div className="flex items-center justify-between">
                  <h3 className="text-2xl font-bold">Starter</h3>
                  <div className="text-4xl font-bold">$29</div>
                </div>
                <p className="text-muted-foreground">Perfect for small businesses and startups.</p>
                <ul className="grid gap-2 text-sm">
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                    Real-time Communications
                  </li>
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                    AI Appointment Scheduling
                  </li>
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                    Client Self-Assessment
                  </li>
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                    CNN Image Assessment
                  </li>
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                    Multi-tenancy and Branding
                  </li>
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                    Analytics and Reporting
                  </li>
                </ul>
                <Button className="w-full">Get Started</Button>
              </div>
              <div className="grid gap-4 p-6 rounded-xl border" />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function ClipboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  )
}


function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}


function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function VideoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>
  )
}
